name: Update Calendar

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: latest
    - name: update Calendar
      run: |
        npm i
        npm run start
      env:
        CI: true
